---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  ubuntu-1604-x64-puppet-master:
    roles: 
    - master
    - dashboard
    - database
    - agent
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales cron'
      - 'locale-gen en_US.UTF-8'
  ubuntu-1604-x64-dns-master:
    roles: 
    - agent
    - default
    - frictionless
    - dnsmaster
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales cron'
      - 'locale-gen en_US.UTF-8'
  ubuntu-1604-x64-slave:
    roles: 
    - agent
    - dnsslave
    - frictionless
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales cron'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
  pe_debug: false
  pe_ver: 2016.4.3
  pe_dir: https://s3.amazonaws.com/pe-builds/released/2016.4.3
...
# vim: syntax=yaml
