stages:
  - lint
  - rubocop
  - rspec
  - beaker_apply
  - beaker_agent

before_script:
  - ruby -v
  - bundle --version
  - gem --version
  - rm Gemfile.lock || true
  - bundle install --path=${BUNDLE_PATH:-vendor/bundle}

lint:
  stage: rspec
  script:
    - bundle exec rake validate lint

rubocop:
  stage: rubocop
  script:
    - bundle exec rake rubocop

rspec:
  stage: rspec
  script:
    - bundle exec rake spec

beaker_trusty_apply:
  stage: beaker_apply
  variables:
    BEAKER_set: docker/ubuntu-14.04
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker

beaker_xenial_apply:
  stage: beaker_apply
  variables:
    BEAKER_set: docker/ubuntu-16.04
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker

beaker_trusty_agent:
  stage: beaker_agent
  variables:
    BEAKER_set: docker/ubuntu-master-14.04
    BEAKER_TESTMODE: agent
  script:
    -  bundle exec rake beaker

beaker_xenial_agent:
  stage: beaker_agent
  variables:
    BEAKER_set: docker/ubuntu-master-16.04
    BEAKER_TESTMODE: agent
  script:
    -  bundle exec rake beaker
